In [ ]:
#step1: import the required libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
data = load_breast_cancer()

X = data.data
y = data.target

print("Feature shape:", X.shape)
print("Label shape:", y.shape)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


Feature shape: (569, 30)
Label shape: (569,)


In [ ]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
svm_linear = SVC(kernel='linear')

svm_linear.fit(X_train, y_train)

y_pred_linear = svm_linear.predict(X_test)



print("Accuracy:", accuracy_score(y_test, y_pred_linear))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_linear))
print("\nClassification Report:\n", classification_report(y_test, y_pred_linear))

Accuracy: 0.9736842105263158

Confusion Matrix:
 [[41  1]
 [ 2 70]]

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.98      0.96        42
           1       0.99      0.97      0.98        72

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



In [ ]:
for i in range(10):
  if y_pred_linear[i] == 1:
    print(f"Sample{i+1}: Benign")
  else:
    print(f"Sample{i+1}: Malignant")

Sample1: Malignant
Sample2: Benign
Sample3: Malignant
Sample4: Malignant
Sample5: Malignant
Sample6: Benign
Sample7: Benign
Sample8: Malignant
Sample9: Malignant
Sample10: Malignant


In [ ]:
svm_rbf = SVC(kernel='rbf')

svm_rbf.fit(X_train, y_train)
y_pred_rbf = svm_rbf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred_rbf))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rbf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rbf))

Accuracy: 0.9824561403508771

Confusion Matrix:
 [[41  1]
 [ 1 71]]

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98        42
           1       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114



In [ ]:
svm_rbf_tuned = SVC(kernel='rbf', C=10, gamma=0.1)

svm_rbf_tuned.fit(X_train, y_train)
y_pred_rbf_tuned = svm_rbf_tuned.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred_rbf_tuned))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rbf_tuned))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rbf_tuned))

Accuracy: 0.9473684210526315

Confusion Matrix:
 [[40  2]
 [ 4 68]]

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.95      0.93        42
           1       0.97      0.94      0.96        72

    accuracy                           0.95       114
   macro avg       0.94      0.95      0.94       114
weighted avg       0.95      0.95      0.95       114

